/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminGalleryEditView: typeof import('./src/views/admin/AdminGalleryEditView.vue')['default']
    AdminLoginView: typeof import('./src/views/AdminLoginView.vue')['default']
    AdminMembersEditView: typeof import('./src/views/admin/AdminMembersEditView.vue')['default']
    AdminOverviewView: typeof import('./src/views/admin/AdminOverviewView.vue')['default']
    AdminPanelView: typeof import('./src/views/AdminPanelView.vue')['default']
    AdminTimelineEditView: typeof import('./src/views/admin/AdminTimelineEditView.vue')['default']
    AdminToolbar: typeof import('./src/components/AdminToolbar.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    ErrorView: typeof import('./src/views/ErrorView.vue')['default']
    ExperienceView: typeof import('./src/views/ExperienceView.vue')['default']
    GalleryView: typeof import('./src/views/GalleryView.vue')['default']
    GlassDialog: typeof import('./src/components/GlassDialog.vue')['default']
    GlassToast: typeof import('./src/components/toast/GlassToast.vue')['default']
    GlassUploadDialog: typeof import('./src/components/GlassUploadDialog.vue')['default']
    GlassUploadDialogTimeline: typeof import('./src/components/GlassUploadDialogTimeline.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    InstallView: typeof import('./src/views/InstallView.vue')['default']
    MembersView: typeof import('./src/views/MembersView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerInfoCard: typeof import('./src/components/home/ServerInfoCard.vue')['default']
    ServerView: typeof import('./src/views/ServerView.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter.vue')['default']
    UpdateNotification: typeof import('./src/components/UpdateNotification.vue')['default']
  }
}
