FROM node:20-bookworm-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=http://localhost:3001
ARG VITE_SITE_NAME=My Server
ARG VITE_SITE_DESCRIPTION=Minecraft Server
ARG VITE_SITE_KEYWORDS=minecraft,server
ARG VITE_SITE_AUTHOR=Admin
ARG VITE_SITE_LOGO=/logo.jpg
ARG VITE_CAESAR_OFFSET=3
ARG VITE_CAESAR_VALID_TOKEN=123456789qwertyu
ARG VITE_AES_SECRET_KEY=123456789qwertyu
ARG VITE_AES_IV=123456789qwertyu
ARG VITE_NETEASE_PLAYLIST_ID=19723756
ARG VITE_AUTO_PLAY=false

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_SITE_NAME=${VITE_SITE_NAME}
ENV VITE_SITE_DESCRIPTION=${VITE_SITE_DESCRIPTION}
ENV VITE_SITE_KEYWORDS=${VITE_SITE_KEYWORDS}
ENV VITE_SITE_AUTHOR=${VITE_SITE_AUTHOR}
ENV VITE_SITE_LOGO=${VITE_SITE_LOGO}
ENV VITE_CAESAR_OFFSET=${VITE_CAESAR_OFFSET}
ENV VITE_CAESAR_VALID_TOKEN=${VITE_CAESAR_VALID_TOKEN}
ENV VITE_AES_SECRET_KEY=${VITE_AES_SECRET_KEY}
ENV VITE_AES_IV=${VITE_AES_IV}
ENV VITE_NETEASE_PLAYLIST_ID=${VITE_NETEASE_PLAYLIST_ID}
ENV VITE_AUTO_PLAY=${VITE_AUTO_PLAY}

RUN npm run build

FROM nginx:1.27-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
